version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: root
  MYSQL_PASSWORD: Tsaniah24*#
  MYSQL_DATABASE: db_todo_list
  REACT_APP_SERVER_PORT: 8000

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/db_todo_list.sql:/docker-entrypoint-initdb.d/db_todo_list.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  server:
    build: ./todo_list_api
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    volumes:
      - ./todo_list_api:/app
    links:
      - mysql-db
    command: npm run start
  client:
    build: ./todo_list_frontend
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./todo_list_frontend/src:/app/src
    links:
      - server
    command: npm run start