version: "3.4"

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/db_todo_list.sql:/docker-entrypoint-initdb.d/db_todo_list.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  server:
    build: ./todo_list_api
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    volumes:
      - ./todo_list_api:/app
    links:
      - mysql-db
    command: npm run start
  client:
    build: ./todo_list_frontend
    container_name: client_container
    environment:
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./todo_list_frontend/src:/app/src
    links:
      - server
    command: npm run start